

objs += \
	$(ROOT)/apps/$(APP_CASE)/record/key/ac696x_demo_record_key.o \
	$(ROOT)/apps/$(APP_CASE)/record/key/ac6969d_demo_record_key.o \
	$(ROOT)/apps/$(APP_CASE)/record/key/ac696x_lighter_record_key.o \

