

objs += \
	$(ROOT)/apps/$(APP_CASE)/linein/key/ac696x_demo_linein_key.o \
	$(ROOT)/apps/$(APP_CASE)/linein/key/ac6969d_demo_linein_key.o \
	$(ROOT)/apps/$(APP_CASE)/linein/key/ac696x_lighter_linein_key.o \



