

ifeq ($(APP_CASE),soundbox)
objs += \
	  $(ROOT)/cpu/$(CPU)/ui_action/STYLE_02/main_action.o \
	  $(ROOT)/cpu/$(CPU)/ui_action/STYLE_02/fm_action.o \
	  $(ROOT)/cpu/$(CPU)/ui_action/STYLE_02/bt_action.o \


endif

	  # $(ROOT)/cpu/$(CPU)/ui_action/lcd_ui.o \
