

ifeq ($(APP_CASE),soundbox)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_mic/mic_stream.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/digital_vol.o \

objs += \
	  $(ROOT)/cpu/$(CPU)/audio_mic/reverb/reverb.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/reverb/reverb_config.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/reverb/reverb_debug.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/echo/echo.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/echo/echo_config.o \

endif
