

objs += \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac6952e_lighter_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac696x_demo_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac6969d_demo_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac695x_ui_demo_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac695x_ui_charging_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac695x_charging_bin_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac696x_lighter_app_common_key.o \
	$(ROOT)/apps/$(APP_CASE)/common/key/ac695x_soundcard_app_common_key.o \
	

