

objs += \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac6952e_lighter_bt_key.o \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac696x_demo_bt_key.o \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac6969d_demo_bt_key.o \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac695x_ui_demo_bt_key.o \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac695x_ui_charging_bt_key.o \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac695x_charging_bin_bt_key.o \
	$(ROOT)/apps/$(APP_CASE)/bt/key/ac696x_lighter_bt_key.o \

