

objs += \
	$(ROOT)/apps/$(APP_CASE)/music/key/ac696x_demo_music_key.o \
	$(ROOT)/apps/$(APP_CASE)/music/key/ac6969d_demo_music_key.o \
	$(ROOT)/apps/$(APP_CASE)/music/key/ac695x_ui_demo_music_key.o \
	$(ROOT)/apps/$(APP_CASE)/music/key/ac695x_ui_charging_music_key.o \
	$(ROOT)/apps/$(APP_CASE)/music/key/ac696x_lighter_music_key.o \

